In [9]:
#PyBank
#Create a dictionary with the values

budget_data = {
'Jan-2010': 867884,
'Feb-2010': 984655,
'Mar-2010': 322013,
'Apr-2010': -69417,
'May-2010': 310503,
'Jun-2010': 522857,
'Jul-2010': 1033096,
'Aug-2010': 604885,
'Sep-2010': -216386,
'Oct-2010': 477532,
'Nov-2010': 893810,
'Dec-2010': -80353,
'Jan-2011': 779806,
'Feb-2011': -335203,
'Mar-2011': 697845,
'Apr-2011': 793163,
'May-2011': 485070,
'Jun-2011': 584122,
'Jul-2011': 62729,
'Aug-2011': 668179,
'Sep-2011': 899906,
'Oct-2011': 834719,
'Nov-2011': 132003,
'Dec-2011': 309978,
'Jan-2012': -755566,
'Feb-2012': 1170593,
'Mar-2012': 252788,
'Apr-2012': 1151518,
'May-2012': 817256,
'Jun-2012': 570757,
'Jul-2012': 506702,
'Aug-2012': -1022534,
'Sep-2012': 475062,
'Oct-2012': 779976,
'Nov-2012': 144175,
'Dec-2012': 542494,
'Jan-2013': 359333,
'Feb-2013': 321469,
'Mar-2013': 67780,
'Apr-2013': 471435,
'May-2013': 565603,
'Jun-2013': 872480,
'Jul-2013': 789480,
'Aug-2013': 999942,
'Sep-2013': -1196225,
'Oct-2013': 268997,
'Nov-2013': -687986,
'Dec-2013': 1150461,
'Jan-2014': 682458,
'Feb-2014': 617856,
'Mar-2014': 824098,
'Apr-2014': 581943,
'May-2014': 132864,
'Jun-2014': 448062,
'Jul-2014': 689161,
'Aug-2014': 800701,
'Sep-2014': 1166643,
'Oct-2014': 947333,
'Nov-2014': 578668,
'Dec-2014': 988505,
'Jan-2015': 1139715,
'Feb-2015': 1029471,
'Mar-2015': 687533,
'Apr-2015': -524626,
'May-2015': 158620,
'Jun-2015': 87795,
'Jul-2015': 423389,
'Aug-2015': 840723,
'Sep-2015': 568529,
'Oct-2015': 332067,
'Nov-2015': 989499,
'Dec-2015': 778237,
'Jan-2016': 650000,
'Feb-2016': -1100387,
'Mar-2016': -174946,
'Apr-2016': 757143,
'May-2016': 445709,
'Jun-2016': 712961,
'Jul-2016': -1163797,
'Aug-2016': 569899,
'Sep-2016': 768450,
'Oct-2016': 102685,
'Nov-2016': 795914,
'Dec-2016': 60988,
'Jan-2017': 138230,
'Feb-2017': 671099,
}

#print profit_loss as a list -- via handy copy and paste from print command line below this
profit_loss_list = [
867884,
984655,
322013,
-69417,
310503,
522857,
1033096,
604885,
-216386,
477532,
893810,
-80353,
779806,
-335203,
697845,
793163,
485070,
584122,
62729,
668179,
899906,
834719,
132003,
309978,
-755566,
1170593,
252788,
1151518,
817256,
570757,
506702,
-1022534,
475062,
779976,
144175,
542494,
359333,
321469,
67780,
471435,
565603,
872480,
789480,
999942,
-1196225,
268997,
-687986,
1150461,
682458,
617856,
824098,
581943,
132864,
448062,
689161,
800701,
1166643,
947333,
578668,
988505,
1139715,
1029471,
687533,
-524626,
158620,
87795,
423389,
840723,
568529,
332067,
989499,
778237,
650000,
-1100387,
-174946,
757143,
445709,
712961,
-1163797,
569899,
768450,
102685,
795914,
60988,
138230,
671099,
]


###### list and dict manipulation
# Iterate over key-value pairs in the Dict
for date, profit_loss in budget_data.items():
    print(f"Date: {date} | profit_loss: {profit_loss}")

# Iterate over key-value pairs in the Dict but print only half to extract a list from the dict, print with a comma afterward too, then insert above
for date, profit_loss in budget_data.items():
    print(f"{profit_loss},")
    

#########


#The total number of months included in the dataset
print(len(budget_data))

#The net total amount of Profit/Losses over the entire period.
    

# Calculate sum of profit/loss by cumulatively summing up the total profits/losses and count of trading days
total_profit_loss = sum(profit_loss_list)

print(f"total_profit_loss: {total_profit_loss}")


#The average of the changes in Profit/Losses over the entire period
# Calculate average Profit/Losses of banks in the dictionary
avg_change_profit_loss = round(total_profit_loss / (len(budget_data)), 2)

print(f"avg_change_profit_loss : {avg_change_profit_loss}")


#The greatest increase in profits (date and amount) over the entire period.

# Initialize the metric variables
count = 0
total = 0
average = 0
minimum = 0
maximum = 0

# Iterate over each profit_loss the list
for indiv_profit_loss in profit_loss_list:
    
 # Cumulatively sum up the total profits/losses and count of trading days
    total = total + indiv_profit_loss
    count += 1
    
# Logic to determine minimum and maximum values
    if minimum == 0:
        minimum = indiv_profit_loss
    elif indiv_profit_loss < minimum:
        minimum = indiv_profit_loss
    elif indiv_profit_loss > maximum:
        maximum = indiv_profit_loss

print(f"minimum: {minimum}")
print(f"maximum: {maximum}")
print(f"count: {count}")

#locate date of greatest increase in original dict  -- I think this didn't work because PANDAS wasn't imported, so I hashed it out and found the date manually below
 #budget_data.loc({maximum})
#locate date of greatest decrease in original dict -- see above
 #budget_data.loc({minimum})

print(f"Financial Analysis: Total Months: " + {count}  + "Total: $" + {total_profit_loss} + "Average  Change: $ " + {avg_change_profit_loss} + "Greatest Increase in Profits: Feb-2012 " + {maximum}, + "Greatest Decrease in Profits: Sep-2013 " + {minimum})

Date: Jan-2010 | profit_loss: 867884
Date: Feb-2010 | profit_loss: 984655
Date: Mar-2010 | profit_loss: 322013
Date: Apr-2010 | profit_loss: -69417
Date: May-2010 | profit_loss: 310503
Date: Jun-2010 | profit_loss: 522857
Date: Jul-2010 | profit_loss: 1033096
Date: Aug-2010 | profit_loss: 604885
Date: Sep-2010 | profit_loss: -216386
Date: Oct-2010 | profit_loss: 477532
Date: Nov-2010 | profit_loss: 893810
Date: Dec-2010 | profit_loss: -80353
Date: Jan-2011 | profit_loss: 779806
Date: Feb-2011 | profit_loss: -335203
Date: Mar-2011 | profit_loss: 697845
Date: Apr-2011 | profit_loss: 793163
Date: May-2011 | profit_loss: 485070
Date: Jun-2011 | profit_loss: 584122
Date: Jul-2011 | profit_loss: 62729
Date: Aug-2011 | profit_loss: 668179
Date: Sep-2011 | profit_loss: 899906
Date: Oct-2011 | profit_loss: 834719
Date: Nov-2011 | profit_loss: 132003
Date: Dec-2011 | profit_loss: 309978
Date: Jan-2012 | profit_loss: -755566
Date: Feb-2012 | profit_loss: 1170593
Date: Mar-2012 | profit_loss: 252788
Date: Apr-2012 | profit_loss: 1151518
Date: May-2012 | profit_loss: 817256
Date: Jun-2012 | profit_loss: 570757
Date: Jul-2012 | profit_loss: 506702
Date: Aug-2012 | profit_loss: -1022534
Date: Sep-2012 | profit_loss: 475062
Date: Oct-2012 | profit_loss: 779976
Date: Nov-2012 | profit_loss: 144175
Date: Dec-2012 | profit_loss: 542494
Date: Jan-2013 | profit_loss: 359333
Date: Feb-2013 | profit_loss: 321469
Date: Mar-2013 | profit_loss: 67780
Date: Apr-2013 | profit_loss: 471435
Date: May-2013 | profit_loss: 565603
Date: Jun-2013 | profit_loss: 872480
Date: Jul-2013 | profit_loss: 789480
Date: Aug-2013 | profit_loss: 999942
Date: Sep-2013 | profit_loss: -1196225
Date: Oct-2013 | profit_loss: 268997
Date: Nov-2013 | profit_loss: -687986
Date: Dec-2013 | profit_loss: 1150461
Date: Jan-2014 | profit_loss: 682458
Date: Feb-2014 | profit_loss: 617856
Date: Mar-2014 | profit_loss: 824098
Date: Apr-2014 | profit_loss: 581943
Date: May-2014 | profit_loss: 132864
Date: Jun-2014 | profit_loss: 448062
Date: Jul-2014 | profit_loss: 689161
Date: Aug-2014 | profit_loss: 800701
Date: Sep-2014 | profit_loss: 1166643
Date: Oct-2014 | profit_loss: 947333
Date: Nov-2014 | profit_loss: 578668
Date: Dec-2014 | profit_loss: 988505
Date: Jan-2015 | profit_loss: 1139715
Date: Feb-2015 | profit_loss: 1029471
Date: Mar-2015 | profit_loss: 687533
Date: Apr-2015 | profit_loss: -524626
Date: May-2015 | profit_loss: 158620
Date: Jun-2015 | profit_loss: 87795
Date: Jul-2015 | profit_loss: 423389
Date: Aug-2015 | profit_loss: 840723
Date: Sep-2015 | profit_loss: 568529
Date: Oct-2015 | profit_loss: 332067
Date: Nov-2015 | profit_loss: 989499
Date: Dec-2015 | profit_loss: 778237
Date: Jan-2016 | profit_loss: 650000
Date: Feb-2016 | profit_loss: -1100387
Date: Mar-2016 | profit_loss: -174946
Date: Apr-2016 | profit_loss: 757143
Date: May-2016 | profit_loss: 445709
Date: Jun-2016 | profit_loss: 712961
Date: Jul-2016 | profit_loss: -1163797
Date: Aug-2016 | profit_loss: 569899
Date: Sep-2016 | profit_loss: 768450
Date: Oct-2016 | profit_loss: 102685
Date: Nov-2016 | profit_loss: 795914
Date: Dec-2016 | profit_loss: 60988
Date: Jan-2017 | profit_loss: 138230
Date: Feb-2017 | profit_loss: 671099
867884,
984655,
322013,
-69417,
310503,
522857,
1033096,
604885,
-216386,
477532,
893810,
-80353,
779806,
-335203,
697845,
793163,
485070,
584122,
62729,
668179,
899906,
834719,
132003,
309978,
-755566,
1170593,
252788,
1151518,
817256,
570757,
506702,
-1022534,
475062,
779976,
144175,
542494,
359333,
321469,
67780,
471435,
565603,
872480,
789480,
999942,
-1196225,
268997,
-687986,
1150461,
682458,
617856,
824098,
581943,
132864,
448062,
689161,
800701,
1166643,
947333,
578668,
988505,
1139715,
1029471,
687533,
-524626,
158620,
87795,
423389,
840723,
568529,
332067,
989499,
778237,
650000,
-1100387,
-174946,
757143,
445709,
712961,
-1163797,
569899,
768450,
102685,
795914,
60988,
138230,
671099,
86
total_profit_loss: 38382578
avg_change_profit_loss : 446309.05
minimum: -1196225
maximum: 1170593
count: 86

TypeError: can only concatenate str (not "set") to str